version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  envisio-backendv2:
    image: envisioapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=test;User Id=postgres;Password=2602;"
    networks:
      - envisioapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "2602"
      POSTGRES_DB: "test"
    networks:
      - envisioapi-dev